### ISSUE TITLE
Dynamic Actions/Buttons

### ISSUE THREAD

**Issue by ScareCrow95** [elgatosf/streamdeck-javascript-sdk#3]
Hello, 
I am working on creating a stream deck integration. We have a web app where you can configure different kinds of overlay (scoreboard, player/team profiles etc). Is it possible to dynamically create actions or update the buttons when we update overlays on our web app, I can get that event inside the js plugin for stream deck with socket io, I was looking for more clarity on dynamically updating the buttons, using a steam deck 15 keys version.

**Comment by ChekTek** [comment]
WebSockets are a great way to communicate with external applications. We do not allow the creation of new keys from outside of Stream Deck, but you can bundle a profile inside your Stream Deck plugin. So one way to dynamically change actions is to bundle a profile. 

- You can create a profile of placeholder actions and bundle it in your plugin.
- Hide the placeholder action from the user by using the flag [VisibleInActionsList](https://developer.elgato.com/documentation/stream-deck/sdk/manifest/#actions)
- Create a visible action that calls [switchToProfile](https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#switchtoprofile) to send users to your bundled profile (keep in mind, you'll want to use [showAlert](https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#showalert) if the user trys to use your action on a device that you did not bundle a profile for).
- You can cache the context of these keys using the [willAppear](https://developer.elgato.com/documentation/stream-deck/sdk/events-received/#willappear)
- Now your plugin can dynamically control what they do!

I'm going to close this, since it's not directly related to the repository, but feel free to continue this discussion over in our newly added [Discussions](https://github.com/orgs/elgatosf/discussions) tab!
