### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by rdohms** [elgatosf/streamdeck-javascript-sdk#5]
Can we make this available as a package in NPM? 
Would make it a lot easier to inject this into projects or allow us to pull in specific files, like the CSS, into other projects or frameworks.

**Comment by tiptronic** [comment]
Since plugins run from the file-system you are not allowed to use `import`, `export` or other module-like features... 

That's why...

BTW: since you run in your own global space throughout your plugin's lifetime, globals are a nice thing... (just think about `window`, `navigator`, and all the other global objects in any Chromium-based environment). 

`$SD` is just a shortcut to keep you from typing things over and over again - it's just there ... and you don't have to mess with it other than using it to quickly access StreamDeck's API, so I don't understand why this would be any better using `import` in this case.

**Comment by tiptronic** [comment]
@theca11 Sorry, I've been unclear with this... I was talking (or at least wanted to talk) about why there's a global `$SD` object...

If you use a recent StreamDeck.app, it's perfectly fine to use modules...

Our SDK is/was backwards compatible to Stream Deck 3 (or 4 - I don't remember), where more restrictions on modules (and other components) applied.

**Comment by ChekTek** [comment]
Stream Deck now offers the capability to run plugins in Node.js as of version 6.5 and we have published libraries on NPM you can find here:

Library: https://www.npmjs.com/package/@elgato/streamdeck
CLI Tool: https://www.npmjs.com/package/@elgato/cli

**Comment by Danielku15** [comment]
@ChekTek  Great to hear and see. Thats how I would have also envisioned it. Any idea when the issue tracker at the [new repo](https://github.com/elgatosf/streamdeck) will be enabled to give feedback? I already ran into some issues and there is some unclarity and the property inspector parts seem missing.

**Comment by GeekyEggo** [comment]
@Danielku15 we’ll be enabling the issue tracker in the coming months as we move closer towards a stable version. Until then, we’d encourage you to join our [Marketplace Maker Discord](https://discord.gg/GehBUcu627), we’ll be happy to answer any questions and assist further there.

Regarding the UI, we’ve got some exciting stuff on the horizon the property inspector. Once this is ready, it will be added to the template.

**Comment by Danielku15** [comment]
@GeekyEggo Thanks for the hints, will ping you folks on Discord then about how I might be able to proceed for my needs. Want to create a new plugin which superceeds https://github.com/tobimori/streamdeck-toggl but I am a bit stuck 😅
